mydata <- read.csv("stat231dataset20892405.csv")
head(mydata)
View(mydata)
user1 <- subset(mydata, subset = (username == "@SimuLiu"))
user2 <- subset(mydata, subset = (username == "@FANEXPOCANADA"))
View(user1)
sum(is.na(mydata[, 1:24]))
history()
mydata$username
mydata[@SimuLiu]
table(mydata$day.of.week)
table(user1$day.of.week)
table(user2$day.of.week)
table(user1$day.of.week)
barplot(table(user1$day.of.week))
barplot(table(factor(user1$day.of.week, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday")
barplot(table(factor(user1$day.of.week, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
barplot(table(user1$day.of.week))
barplot(table(factor(user1$day.of.week, levels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
barplot(table(factor(user1$day.of.week, levels = c("Mon", "Tues", "Wed", "Thurs","Fri", "Sat", "Sun"))))
barplot(table(factor(user1$day.of.week, levels = c("Mon", "Tues", "Wed", "Thurs","Fri", "Sat", "Sun"))))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"), las = 2)))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))las = 2))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday")))las = 2)
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday","Friday", "Saturday", "Sunday"))), x=lab = "Day")
barplot(table)
barplot(table(user1$day.of.week), xlab = "Day")
barplot(table(user1$day.of.week), xlab = "Day", las = 2)
barplot(table(user1$day.of.week), xlab = "Day", las = 2, ylim = c(0, 50))
barplot(table(factor(user1$day.of.week, levels = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"))), xlab = "Day", las = 2, ylim = c(0, 50))
barplot(table(user1$day.of.week), xlab = "Day", las = 2)
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"))
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25)
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25, main = "Barplot of Tweets Each Day", ylab = "# of Tweets")
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25, main = "Barplot of Tweets Each Day", ylab = "# Of Tweets")
barplot(table(factor(user2$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25, main = "Barplot of Tweets Each Day", ylab = "# Of Tweets")
barplot(table(factor(user1$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25, main = "Barplot of Tweets Each Day For @SimuLiu", ylab = "# Of Tweets")
barplot(table(factor(user2$day.of.week, levels = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))), xlab = "Day", names.arg = c("Mon", "Tues", "Wed", "Thurs", "Fri", "Sat", "Sun"), ylim = c(0, 50), col = c("red", "green", "yellow", "orange", "brown", "cyan", "grey"), density = 25, main = "Barplot of Tweets Each Day For @FANEXPOCANADA", ylab = "# Of Tweets")
mydata$time.of.day.hour <- mydata$time.of.day/3600
mydata$time.of.day.hour
View(user2)
user1$time.of.day.hour <- user1$time.of.day/3600
user2$time.of.day.hour <- user2$time.of.day/3600
user1
View(user1)
user1$time.of.day.hour
View(user2)
user2$time.of.day.hour
mean(user1$time.of.day.hour)
sd(user1$time.of.day.hour)
skewness <- function(x) {(sum((x - mean(x))ˆ3)/length(x))/(sum((x - mean(x))ˆ2)/length(x))ˆ(3/2)}
kurtosis <- function(x) {(sum((x - mean(x))ˆ4)/length(x))/(sum((x - mean(x))ˆ2)/length(x))ˆ2}
skewness <- function(x){(sum((x - mean(x))^3)/length(x))/(sum((x-mean(x))^2)/length(x))^(3/2)}
kurtosis <- function(x){(sum((x-mean(x))^4)/length(x))/(sum((x-mean(x))^2)/length(x))^2}
skewness(user1$time.of.day.hour)
kurtosis(user1$time.of.day.hour)
median(user1$time.of.day.hour)
mean(user2$time.of.day.hour)
median(user2$time.of.day.hour)
sd(user2$time.of.day.hour)
skewness(user2$time.of.day.hour)
kurtosis(user2$time.of.day.hour)
kurtosis(user1$time.of.day.hour)
skewness(user1$time.of.day.hour)
user1mean <- mean(user1$time.of.day.hour)
user2mean <- mean(user2$time.of.day.hour)
user1sd <- sd(user1$time.of.day.hour)
user2sd <- sd(user2$time.of.day.hour)
user1skew <- skewness(user1$time.of.day.hour)
user2skew <- skewness(user2$time.of.day.hour)
user1kurt <- kurtosis(user1$time.of.day.hour)
user2kurt <- kurtosis(user2$time.of.day.hour)
user1med <- median(user1$time.of.day.hour)
user2med <- median(user2$time.of.day.hour)
library(MASS)
truehist
truehist(user1$time.of.day.hour)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day")
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted")
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 25)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 40)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.05))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.10))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.75))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.075))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.06))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.06), nbins = 10)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.06))
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, ylim = c(0, 0.06), nbins = 10)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, xlim = c(0, 25), ylim = c(0, 0.06), nbins = 10)
curve(dnorm(x, user1mean, user1sd) col = "red", add = TRUE, lwd = 3)
curve(dnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 3)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, xlim = c(0, 25), ylim = c(0, 0.065), nbins = 10)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, xlim = c(0, 25), ylim = c(0, 0.080), nbins = 10)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, xlim = c(0, 25), ylim = c(0, 0.070), nbins = 10)
curve(dnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 3)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted", density = 30, xlim = c(0, 25), ylim = c(0, 0.070), nbins = 10)
truehist(user1$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @SimuLiu", density = 30, xlim = c(0, 25), ylim = c(0, 0.070), nbins = 10)
curve(dnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 3)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.070), nbins = 10)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.090), nbins = 10)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.1), nbins = 10)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.15), nbins = 10)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.16), nbins = 10)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.16), nbins = 8)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.16), nbins = 5)
truehist(user2$time.of.day.hour, ylab = "Relative Frequency", xlab = "Time of Day", main = "Relative Frequency Histogram of Time of Day Tweeted For @FANEXPOCANADA", density = 30, xlim = c(0, 25), ylim = c(0, 0.16), nbins = 10)
max(user2$time.of.day.hour)
curve(dnorm(x, user2mean, user2sd), col = "red", add = TRUE, lwd = 3)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu")
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", las = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu")
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", las = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu")
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", las = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu")
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = "TRUE", lwd = 1.5, lty = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = "TRUE", lwd = 1.5, lty = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = "TRUE", lwd = 1.5, lty = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = "TRUE", lwd = 1.5, lty = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 1.5, lty = 2)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 2, lty = 2)
plot(ecdf(user2$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @FANEXPOCANADA", lwd = 2, pch = NA)
curve(pnorm(x, user2mean, user2sd), col = "red", add = TRUE, lwd = 2, lty = 2)
quauntile(user1$time.of.day.hour, prob = .1)
quantile(user1$time.of.day.hour, prob = .1)
plot(ecdf(user1$time.of.day.hour), xlab = "Time of Day", main = "E.C.D.F of Time of Day Tweeted for @SimuLiu", lwd = 2, pch = NA)
curve(pnorm(x, user1mean, user1sd), col = "red", add = TRUE, lwd = 2, lty = 2)
quantile(user2$time.of.day.hour, prob = .1)
quantile(user1$time.of.day.hour, prob = .1)
user1$likes.log <-log(user1$likes + 1)
user1$likes.log

